base_url = "https://www.student.dtu.dk/~s203871/"
title = "Johannes Nørskov Toke"
description = "Loudspeakers • ML • Acoustics"
theme = "terminimal"
compile_sass = true            # Terminimal uses Sass, so this must be true
minify_html = true
default_language = "en"

[extra]
# Theme colors (you can change these if you want a different vibe)
accent_color = "orange"         # options: blue, green, orange, pink, red
background_color = "dark"      # options: dark, light, auto, blue, green, orange, pink, red

author = "Johannes Nørskov Toke"
logo_text = "Johannes N. Toke"
logo_home_link = "/"

# Top navigation menu
menu_items = [
  { name = "home", url = "$BASE_URL/" },
  { name = "master", url = "$BASE_URL/master/", submenu = [{ name = "research question", url = "$BASE_URL/master/mindmap/" }, { name = "plan", url = "$BASE_URL/master/plan/" }, { name = "results", url = "$BASE_URL/master/results/" }] },
  { name = "github", url = "https://github.com/johtok", newtab = true },
  { name = "linkedin", url = "https://www.linkedin.com/in/johannes-n%C3%B8rskov-t-6b3a24134/", newtab = true },
  { name = "email", url = "mailto:s203871@student.dtu.dk" }
]

# Optional extras Terminimal supports:
page_titles = "combined"
use_full_hack_font = false
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"
# default_og_image = "/some-image.jpg"
